### ISSUE TITLE
Error LNK2019

### ISSUE THREAD

**Issue by Smkash3112** [azerothcore/mod-progression-system#288]

**Comment by 55Honey** [comment]
@Smkash3112 please don't delete the texts of your issues. it's bad practice and the whole text is still visible to everyone. They just need to click a button to go back a revision.
If you don't care anymore, you can just add that.
If you solved it, feel free to post how, so the next user has a way to find your solution.

Your problem is that you did not remove the `-master` added by github when downloading zip files. See step 4 of https://www.azerothcore.org/wiki/add-a-module
